version: '3.4'
services:
  wordpress:
    image: wordpress:6.7.2-php8.4-fpm
    restart: always
    ports:
      - 8088:80
    env_file:
      - ./.wordpress
    volumes:
      - ./wordpress:/var/www/html
  db:
    image: mariadb:11.7.2
    restart: always
    env_file:
      - ./.wordpress
    volumes:
      - ./db:/var/lib/mysql