version: '3.4'
services:
  wordpress:
    image: wordpress:6.7.2-php8.4-fpm
    container_name: bs-wp
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - ./.wordpress
    volumes:
      - ./wordpress:/var/www/html
  db:
    image: mariadb:11.7.2
    container_name: bs-db
    restart: unless-stopped
    env_file:
      - ./.wordpress
    volumes:
      - ./db:/var/lib/mysql
  
  nginx:
    image: nginx:1.27.4
    container_name: bs-nginx
    env_file:
      - ./.wordpress
    restart: unless-stopped
    depends_on:
      - wordpress
    ports:
      - "8088:80" 
    volumes:
      - ./wordpress:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx